window.adTranslations = {
  pl: {
    'ads.previous':'Poprzednie reklamy', 'ads.next':'Następne reklamy', 'ads.previousMonth':'Poprzedni miesiąc', 'ads.nextMonth':'Następny miesiąc',
    'ads.order':'Zamów ogłoszenie', 'ads.top':'Polecane firmy', 'ads.sponsors':'Reklamy', 'ads.sponsored':'Reklama', 'ads.pause':'Wstrzymaj', 'ads.play':'Wznów',
    'ads.intro':'Wybierz rynek i termin. Po wysłaniu zamówienie trafi do redakcji do akceptacji. Na tym etapie nie pobieramy płatności online.',
    'ads.market':'Język / rynek', 'ads.type':'Rodzaj reklamy', 'ads.start':'Pierwszy dzień', 'ads.end':'Ostatni dzień (włącznie)', 'ads.month':'Kalendarz dostępności',
    'ads.legend':'Zielony: dostępne · żółty: ostatnie miejsca · szary: niedostępne. Kliknij pierwszy, a następnie ostatni dzień. Liczby oznaczają wolne miejsca.',
    'ads.company':'Firma / reklamodawca', 'ads.title':'Tytuł reklamy', 'ads.description':'Krótki opis', 'ads.image':'Grafika / logo (PNG, JPEG, WebP, do 500 KB)', 'ads.url':'Adres strony reklamy', 'ads.email':'E-mail kontaktowy', 'ads.phone':'Telefon (opcjonalnie)', 'ads.customerName':'Imię i nazwisko zamawiającego',
    'ads.consent':'Zgadzam się na przetwarzanie podanych danych w celu obsługi tego zamówienia.', 'ads.review':'Sprawdź podsumowanie', 'ads.send':'Wyślij zamówienie', 'ads.back':'Wróć do edycji', 'ads.summary':'Podsumowanie', 'ads.days':'dni', 'ads.total':'Razem', 'ads.loading':'Sprawdzanie dostępności…', 'ads.success':'Zamówienie zapisane. Status: oczekuje. Numer zamówienia:', 'ads.pendingInfo':'Oczekujące zamówienia rezerwują miejsca do decyzji redakcji.',
    'ads.error.unavailable':'Usługa reklam jest chwilowo niedostępna. Spróbuj ponownie później.', 'ads.error.disabled':'Zamawianie reklam dla tego języka jest wyłączone.', 'ads.error.full':'Brak miejsc w dniach:', 'ads.error.dates':'Wybierz poprawny zakres od dzisiaj: maksymalnie 366 dni, nie dalej niż 2 lata.', 'ads.error.validation':'Sprawdź wszystkie dane formularza.', 'ads.error.image':'Wybierz poprawny plik PNG, JPEG lub WebP do 500 KB.', 'ads.error.priceChanged':'Cennik zmienił się. Sprawdź nową cenę i ponownie zatwierdź podsumowanie.', 'ads.error.conflict':'Dane zmieniły się. Odśwież widok i spróbuj ponownie.', 'ads.error.rateLimit':'Osiągnięto limit zgłoszeń. Spróbuj ponownie za godzinę.', 'ads.error.market':'Nieprawidłowy język lub typ reklamy.'
  },
  fr: {
    'ads.previous':'Publicités précédentes', 'ads.next':'Publicités suivantes', 'ads.previousMonth':'Mois précédent', 'ads.nextMonth':'Mois suivant',
    'ads.order':'Commander une annonce', 'ads.top':'Entreprises à découvrir', 'ads.sponsors':'Publicités', 'ads.sponsored':'Publicité', 'ads.pause':'Pause', 'ads.play':'Reprendre',
    'ads.intro':'Choisissez le marché et les dates. Votre commande sera soumise à la rédaction pour approbation. Aucun paiement en ligne à cette étape.',
    'ads.market':'Langue / marché', 'ads.type':'Type de publicité', 'ads.start':'Premier jour', 'ads.end':'Dernier jour (inclus)', 'ads.month':'Calendrier des disponibilités',
    'ads.legend':'Vert : disponible · jaune : dernières places · gris : indisponible. Cliquez sur le premier puis le dernier jour. Les chiffres indiquent les places restantes.',
    'ads.company':'Entreprise / annonceur', 'ads.title':'Titre', 'ads.description':'Description courte', 'ads.image':'Image / logo (PNG, JPEG, WebP, 500 Ko maximum)', 'ads.url':'Adresse du site', 'ads.email':'E-mail de contact', 'ads.phone':'Téléphone (facultatif)', 'ads.customerName':'Nom du client',
    'ads.consent':'Je consens au traitement de mes données pour gérer cette commande.', 'ads.review':'Vérifier le récapitulatif', 'ads.send':'Envoyer la commande', 'ads.back':'Modifier', 'ads.summary':'Récapitulatif', 'ads.days':'jours', 'ads.total':'Total', 'ads.loading':'Vérification des disponibilités…', 'ads.success':'Commande enregistrée. Statut : en attente. Numéro :', 'ads.pendingInfo':'Les commandes en attente réservent les places jusqu’à la décision de la rédaction.',
    'ads.error.unavailable':'Le service est temporairement indisponible. Réessayez plus tard.', 'ads.error.disabled':'Les commandes sont désactivées pour cette langue.', 'ads.error.full':'Aucune place aux dates suivantes :', 'ads.error.dates':'Choisissez une période à partir d’aujourd’hui : 366 jours maximum, dans les deux prochaines années.', 'ads.error.validation':'Vérifiez les données du formulaire.', 'ads.error.image':'Choisissez un fichier PNG, JPEG ou WebP valide de 500 Ko maximum.', 'ads.error.priceChanged':'Les tarifs ont changé. Vérifiez le nouveau prix et confirmez à nouveau.', 'ads.error.conflict':'Les données ont changé. Actualisez et réessayez.', 'ads.error.rateLimit':'Limite de commandes atteinte. Réessayez dans une heure.', 'ads.error.market':'Langue ou type de publicité incorrect.'
  },
  nl: {
    'ads.previous':'Vorige advertenties', 'ads.next':'Volgende advertenties', 'ads.previousMonth':'Vorige maand', 'ads.nextMonth':'Volgende maand',
    'ads.order':'Advertentie bestellen', 'ads.top':'Uitgelichte bedrijven', 'ads.sponsors':'Advertenties', 'ads.sponsored':'Advertentie', 'ads.pause':'Pauzeren', 'ads.play':'Hervatten',
    'ads.intro':'Kies de markt en de datums. De redactie beoordeelt uw bestelling. In deze stap wordt geen online betaling gevraagd.',
    'ads.market':'Taal / markt', 'ads.type':'Advertentietype', 'ads.start':'Eerste dag', 'ads.end':'Laatste dag (inclusief)', 'ads.month':'Beschikbaarheidskalender',
    'ads.legend':'Groen: beschikbaar · geel: laatste plaatsen · grijs: niet beschikbaar. Klik op de eerste en daarna de laatste dag. Cijfers tonen de resterende plaatsen.',
    'ads.company':'Bedrijf / adverteerder', 'ads.title':'Titel', 'ads.description':'Korte beschrijving', 'ads.image':'Afbeelding / logo (PNG, JPEG, WebP, maximaal 500 KB)', 'ads.url':'Websiteadres', 'ads.email':'Contact-e-mail', 'ads.phone':'Telefoon (optioneel)', 'ads.customerName':'Naam van de klant',
    'ads.consent':'Ik stem in met de verwerking van mijn gegevens voor deze bestelling.', 'ads.review':'Overzicht controleren', 'ads.send':'Bestelling verzenden', 'ads.back':'Bewerken', 'ads.summary':'Overzicht', 'ads.days':'dagen', 'ads.total':'Totaal', 'ads.loading':'Beschikbaarheid controleren…', 'ads.success':'Bestelling opgeslagen. Status: in afwachting. Bestelnummer:', 'ads.pendingInfo':'Bestellingen in afwachting reserveren plaatsen tot de redactie beslist.',
    'ads.error.unavailable':'De dienst is tijdelijk niet beschikbaar. Probeer het later opnieuw.', 'ads.error.disabled':'Bestellen is uitgeschakeld voor deze taal.', 'ads.error.full':'Geen plaatsen op:', 'ads.error.dates':'Kies een periode vanaf vandaag: maximaal 366 dagen, binnen de komende twee jaar.', 'ads.error.validation':'Controleer alle formuliergegevens.', 'ads.error.image':'Kies een geldig PNG-, JPEG- of WebP-bestand van maximaal 500 KB.', 'ads.error.priceChanged':'De tarieven zijn gewijzigd. Controleer de nieuwe prijs en bevestig opnieuw.', 'ads.error.conflict':'De gegevens zijn gewijzigd. Vernieuw en probeer opnieuw.', 'ads.error.rateLimit':'Bestellimiet bereikt. Probeer het over een uur opnieuw.', 'ads.error.market':'Ongeldige taal of ongeldig advertentietype.'
  }
};
