(() => {
  const copy = {
    pl: { title:'Zamów ogłoszenie', intro:'Wybierz języki, format i dni. Dodaj treść — cenę zobaczysz od razu.', languages:'1. Języki ogłoszenia', type:'2. Miejsce publikacji', top:'TOP — nad stroną główną', standard:'STANDARD — sekcja ogłoszeń', dates:'3. Zaznacz dni w kalendarzu', hint:'Kliknij dowolne dostępne dni. Ponowne kliknięcie usuwa dzień. Maksymalnie 90 dni.', choose:'Najpierw wybierz język i rodzaj reklamy.', texts:'4. Treść ogłoszenia', prompts:['Tutaj umieść ogłoszenie w języku polskim','Tutaj umieść ogłoszenie w języku niderlandzkim','Tutaj umieść ogłoszenie w języku francuskim'], contact:'Kontakt widoczny pod ogłoszeniem', contactHint:'Telefon, e-mail lub adres — wpisz to, co chcesz upublicznić.', email:'Twój e-mail — tylko dla administratorów', privacy:'Ten adres nie pojawi się w ogłoszeniu. Służy do kontaktu w sprawie zamówienia.', consent:'Zgadzam się na publikację wpisanej treści i kontaktu oraz przetwarzanie e-maila w celu obsługi zamówienia.', total:'Łącznie', days:'Wybrane dni', review:'Sprawdź zamówienie', send:'Złóż zamówienie', back:'Wróć do edycji', close:'Zamknij', loading:'Sprawdzanie dostępności…', unavailable:'Zamawianie w wybranym języku jest obecnie wyłączone.', error:'Nie udało się pobrać danych. Spróbuj ponownie.', full:'Wybrane miejsca zostały zajęte. Wybierz inne dni.', changed:'Cena zmieniła się. Sprawdź nową cenę przed wysłaniem.', success:'Zamówienie zapisane. Oczekuje na akceptację administratora.', unpaid:'Płatności online nie są jeszcze dostępne. Teraz nic nie płacisz; złożenie zamówienia nie oznacza publikacji.', empty:'Wybierz co najmniej jeden dostępny dzień.', previous:'Poprzedni miesiąc', next:'Następny miesiąc', limit:'Możesz wybrać maksymalnie 90 dni.' },
    fr: { title:'Publier une annonce', intro:'Choisissez les langues, le format et les jours. Ajoutez votre texte : le prix est calculé immédiatement.', languages:'1. Langues de l’annonce', type:'2. Emplacement', top:'TOP — en haut de la page d’accueil', standard:'STANDARD — rubrique annonces', dates:'3. Sélectionnez les jours', hint:'Cliquez sur les jours disponibles. Cliquez à nouveau pour retirer un jour. Maximum 90 jours.', choose:'Choisissez d’abord une langue et un format.', texts:'4. Texte de l’annonce', prompts:['Saisissez ici votre annonce en polonais','Saisissez ici votre annonce en néerlandais','Saisissez ici votre annonce en français'], contact:'Coordonnées affichées sous l’annonce', contactHint:'Téléphone, e-mail ou adresse : indiquez ce que vous souhaitez rendre public.', email:'Votre e-mail — réservé aux administrateurs', privacy:'Cette adresse ne sera pas publiée. Elle sert au suivi de votre commande.', consent:'J’accepte la publication du texte et des coordonnées saisis ainsi que le traitement de mon e-mail pour gérer la commande.', total:'Total', days:'Jours sélectionnés', review:'Vérifier la commande', send:'Envoyer la commande', back:'Modifier', close:'Fermer', loading:'Vérification des disponibilités…', unavailable:'Les commandes sont actuellement désactivées pour cette langue.', error:'Impossible de charger les données. Veuillez réessayer.', full:'Les emplacements sélectionnés ne sont plus disponibles. Choisissez d’autres jours.', changed:'Le prix a changé. Vérifiez le nouveau montant.', success:'Commande enregistrée. Elle attend l’approbation de l’administrateur.', unpaid:'Le paiement en ligne sera disponible ultérieurement. Aucun paiement maintenant ; la commande ne vaut pas publication.', empty:'Sélectionnez au moins un jour disponible.', previous:'Mois précédent', next:'Mois suivant', limit:'Vous pouvez sélectionner 90 jours au maximum.' },
    nl: { title:'Plaats een advertentie', intro:'Kies talen, formaat en dagen. Voeg je tekst toe: je ziet meteen de prijs.', languages:'1. Talen van de advertentie', type:'2. Plaatsing', top:'TOP — bovenaan de startpagina', standard:'STANDARD — advertentierubriek', dates:'3. Selecteer dagen', hint:'Klik op beschikbare dagen. Klik opnieuw om een dag te verwijderen. Maximaal 90 dagen.', choose:'Kies eerst een taal en een advertentietype.', texts:'4. Advertentietekst', prompts:['Plaats hier je advertentie in het Pools','Plaats hier je advertentie in het Nederlands','Plaats hier je advertentie in het Frans'], contact:'Contactgegevens onder de advertentie', contactHint:'Telefoon, e-mail of adres: vul in wat openbaar mag zijn.', email:'Je e-mail — alleen voor beheerders', privacy:'Dit adres wordt niet gepubliceerd. We gebruiken het voor vragen over je bestelling.', consent:'Ik ga akkoord met publicatie van de tekst en contactgegevens en verwerking van mijn e-mail voor deze bestelling.', total:'Totaal', days:'Geselecteerde dagen', review:'Controleer bestelling', send:'Bestelling plaatsen', back:'Bewerken', close:'Sluiten', loading:'Beschikbaarheid controleren…', unavailable:'Bestellen in deze taal is momenteel uitgeschakeld.', error:'Gegevens laden mislukt. Probeer opnieuw.', full:'De gekozen plaatsen zijn niet meer beschikbaar. Kies andere dagen.', changed:'De prijs is gewijzigd. Controleer het nieuwe bedrag.', success:'Bestelling opgeslagen. Deze wacht op goedkeuring door de beheerder.', unpaid:'Online betalen is nog niet beschikbaar. Je betaalt nu niets; bestellen betekent nog geen publicatie.', empty:'Selecteer ten minste één beschikbare dag.', previous:'Vorige maand', next:'Volgende maand', limit:'Je kunt maximaal 90 dagen selecteren.' }
  };
  const keys=['pl','nl','fr'], names=['Polski','Nederlands','Français'];
  const dialog=document.createElement('dialog'); dialog.id='order-dialog'; dialog.setAttribute('aria-labelledby','order-title'); document.body.append(dialog);
  let config, selected=new Set(), selectedLanguages=['pl'], type='', month='', drafts={}, contact='', email='', requestId=crypto.randomUUID(), version=0, pending=false, restoreFocus, locale='pl';
  const $=s=>dialog.querySelector(s), t=k=>copy[locale][k], money=n=>new Intl.NumberFormat(locale,{style:'currency',currency:'EUR'}).format(n/100);
  const node=(tag,text,className)=>{const e=document.createElement(tag);e.textContent=text;if(className)e.className=className;return e;};
  async function api(action,params={},body){const r=await fetch('/.netlify/functions/ads?'+new URLSearchParams({action,...params}),body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error);return data;}
  function capture(){dialog.querySelectorAll('[data-copy]').forEach(e=>drafts[e.dataset.copy]=e.value);contact=$('[name=contact]')?.value||contact;email=$('[name=email]')?.value||email;}
  function total(){return !config||!type?0:selected.size*selectedLanguages.reduce((sum,l)=>sum+config.data.markets[l].prices[type],0);}
  function error(e){$('#order-message').textContent=t(({disabled:'unavailable',full:'full',priceChanged:'changed'})[e.message]||'error');}
  function summary(){const list=$('#chosen-days');list.replaceChildren(...[...selected].sort().map(date=>{const b=node('button',new Intl.DateTimeFormat(locale,{day:'numeric',month:'short'}).format(new Date(date+'T12:00:00')),'chosen-day');b.type='button';b.onclick=()=>{selected.delete(date);summary();calendar();};return b;}));$('#order-total').textContent=money(total());$('#order-review').disabled=!selected.size||!selectedLanguages.length||!type||!config;}
  function texts(){capture();const box=$('#order-texts');box.replaceChildren();for(const l of selectedLanguages){const label=node('label',copy[locale].prompts[keys.indexOf(l)]);const input=document.createElement('textarea');input.dataset.copy=l;input.maxLength=400;input.required=true;input.rows=4;input.value=drafts[l]||'';const count=node('small',`${input.value.length}/400`);input.oninput=()=>{drafts[l]=input.value;count.textContent=`${input.value.length}/400`;requestId=crypto.randomUUID();};label.append(input,count);box.append(label);}}
  async function calendar(){const serial=++version;const grid=$('#order-calendar');grid.replaceChildren();$('#order-calendar-step').hidden=!type||!selectedLanguages.length;summary();if(!type||!selectedLanguages.length||!config)return;
    $('#order-message').textContent='';$('#calendar-status').textContent=t('loading');const [year,m]=month.split('-').map(Number);$('#order-month-label').textContent=new Intl.DateTimeFormat(locale,{month:'long',year:'numeric'}).format(new Date(year,m-1,1));
    const start=month+'-01',end=new Date(Date.UTC(year,m,0)).toISOString().slice(0,10);if(end<config.today){$('#calendar-status').textContent='';return;}
    try{const availability=await Promise.all(selectedLanguages.map(language=>api('availability',{language,type,startDate:start<config.today?config.today:start,endDate:end})));if(serial!==version)return;
      $('#calendar-status').textContent='';const first=new Date(year,m-1,1);for(let n=0;n<7;n++)grid.append(node('span',new Intl.DateTimeFormat(locale,{weekday:'short'}).format(new Date(2026,5,1+n)),'calendar-weekday'));
      for(let n=0;n<(first.getDay()+6)%7;n++)grid.append(node('span',''));
      for(let day=1;day<=Number(end.slice(-2));day++){const date=`${month}-${String(day).padStart(2,'0')}`;const free=date>=config.today&&availability.every(a=>a.daysAvailable.some(d=>d.date===date&&d.remaining>0));const b=node('button',String(day));b.type='button';b.dataset.date=date;b.disabled=!free;b.setAttribute('aria-label',new Intl.DateTimeFormat(locale,{dateStyle:'full'}).format(new Date(date+'T12:00:00')));b.setAttribute('aria-pressed',String(selected.has(date)));b.onclick=()=>{if(selected.has(date))selected.delete(date);else if(selected.size<90)selected.add(date);else $('#order-message').textContent=t('limit');requestId=crypto.randomUUID();b.setAttribute('aria-pressed',String(selected.has(date)));summary();};grid.append(b);}
    }catch(e){if(serial===version){$('#calendar-status').textContent='';selected.clear();summary();error(e);}}
  }
  function render(){dialog.innerHTML=`<div class="order-heading"><div><span class="eyebrow">Polacy w Belgii</span><h2 id="order-title">${t('title')}</h2></div><button type="button" id="order-close" aria-label="${t('close')}">×</button></div><p>${t('intro')}</p><p id="order-message" role="status"></p><form id="order-form"><div class="order-options"><fieldset><legend>${t('languages')}</legend>${keys.map((l,i)=>`<label class="order-choice"><input type="checkbox" name="languages" value="${l}" ${selectedLanguages.includes(l)?'checked':''}>${names[i]}</label>`).join('')}</fieldset><fieldset><legend>${t('type')}</legend>${['TOP','STANDARD'].map(v=>`<label class="order-choice"><input type="radio" name="type" value="${v}" ${type===v?'checked':''}>${t(v==='TOP'?'top':'standard')}</label>`).join('')}</fieldset></div><p>${t('choose')}</p><fieldset id="order-calendar-step" hidden><legend>${t('dates')}</legend><p>${t('hint')}</p><div class="order-month"><button type="button" id="month-prev" aria-label="${t('previous')}">‹</button><strong id="order-month-label"></strong><button type="button" id="month-next" aria-label="${t('next')}">›</button></div><p id="calendar-status" role="status"></p><div id="order-calendar"></div><p>${t('days')}: <span id="chosen-days"></span></p></fieldset><fieldset><legend>${t('texts')}</legend><div id="order-texts"></div><label>${t('contact')}<input name="contact" maxlength="160" required><small>${t('contactHint')}</small></label><label>${t('email')}<input name="email" type="email" maxlength="254" required autocomplete="email"><small>${t('privacy')}</small></label></fieldset><label class="order-choice"><input name="consent" type="checkbox" required>${t('consent')}</label><div class="order-total"><span>${t('total')}</span><strong id="order-total"></strong></div><p class="order-note">${t('unpaid')}</p><button class="button" id="order-review" disabled>${t('review')}</button></form><section id="order-confirm" hidden></section>`;
    $('[name=contact]').value=contact;$('[name=email]').value=email;texts();summary();$('#order-close').onclick=()=>dialog.close();
    dialog.querySelectorAll('[name=languages],[name=type]').forEach(e=>e.onchange=()=>{capture();selectedLanguages=keys.filter(l=>dialog.querySelector(`[name=languages][value=${l}]`).checked);type=dialog.querySelector('[name=type]:checked')?.value||'';selected.clear();requestId=crypto.randomUUID();texts();calendar();});
    for(const [id,delta] of [['month-prev',-1],['month-next',1]])$('#'+id).onclick=()=>{const [y,m]=month.split('-').map(Number);const next=new Date(Date.UTC(y,m-1+delta,1)).toISOString().slice(0,7);if(next>=config.today.slice(0,7)&&next<=new Date(Date.parse(config.today)+86400000*700).toISOString().slice(0,7)){month=next;calendar();}};
    $('#order-form').onsubmit=e=>{e.preventDefault();capture();if(!selected.size)return;const box=$('#order-confirm');box.replaceChildren(node('h3',t('review')));for(const l of selectedLanguages){box.append(node('h4',names[keys.indexOf(l)]),node('p',drafts[l]));}box.append(node('p',contact),node('p',email),node('p',`${type} · ${[...selected].sort().join(', ')}`),node('strong',money(total())),node('p',t('unpaid')));const back=node('button',t('back'),'order-back'),send=node('button',t('send'),'button');back.type=send.type='button';back.onclick=()=>{$('#order-form').hidden=false;box.hidden=true;};send.onclick=async()=>{if(pending)return;pending=true;send.disabled=back.disabled=true;const body={requestId,type,dates:[...selected].sort(),variants:selectedLanguages.map(language=>({language,text:drafts[language]})),contact,email,consent:true,expectedTotalPrice:total()};try{const result=await api('order-batch',{},body);box.replaceChildren(node('h3',t('success')),node('p',result.id),node('p',t('unpaid')));selected.clear();drafts={};requestId=crypto.randomUUID();}catch(err){error(err);if(['priceChanged','full','disabled'].includes(err.message)){config=await api('config');box.hidden=true;$('#order-form').hidden=false;calendar();}}finally{pending=false;send.disabled=back.disabled=false;}};box.append(back,send);$('#order-form').hidden=true;box.hidden=false;send.focus();};calendar();
  }
  async function open(trigger){if(dialog.open)return;restoreFocus=trigger;locale=copy[document.documentElement.lang]?document.documentElement.lang:'pl';dialog.innerHTML='<p>'+t('loading')+'</p>';dialog.showModal();document.body.classList.add('order-open');try{config=await api('config');month=month||config.today.slice(0,7);render();}catch{dialog.replaceChildren(node('p',t('error')));const close=node('button',t('close'));close.onclick=()=>dialog.close();dialog.append(close);}}
  document.addEventListener('click',e=>{const trigger=e.target.closest('[data-order-open],a[href="/zamow-ogloszenie/"]');if(trigger){e.preventDefault();open(trigger);}});
  dialog.addEventListener('close',()=>{capture();version++;document.body.classList.remove('order-open');restoreFocus?.focus();});
  document.addEventListener('languagechange',()=>{if(dialog.open){capture();locale=copy[document.documentElement.lang]?document.documentElement.lang:'pl';render();}});
  if(location.pathname==='/zamow-ogloszenie/')open(document.querySelector('[data-order-open]'));
})();
